sonar.projectKey=EV-Service-Center
sonar.projectName=EV Service Center
sonar.projectVersion=1.0

sonar.sources=services,frontend
sonar.tests=services,frontend-tests

sonar.test.inclusions=**/tests/**,**/*test*.py,**/*.spec.js

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.python.coverage.reportPaths=services/**/coverage.xml

sonar.exclusions=**/__pycache__/**,\
**/.pytest_cache/**,\
**/node_modules/**,\
**/playwright-report/**,\
**/test-results/**,\
**/htmlcov/**,\
**/*.pyc,\
**/migrations/**,\
**/.git/**