name: Backup Postman Collection

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download collection from Postman
        run: |
          curl --location \
            --request GET "https://api.getpostman.com/collections/55036832-a67f4af8-07c1-4e81-8a3e-376d1f3170a3" \
            --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            --output collection.json

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add collection.json

          git diff --cached --quiet || (
            git commit -m "Auto backup Postman collection"
            git push
          )
