name: Postman API Tests with Jira

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Start Docker services
        working-directory: EV-sever-center-main/EV-Service-Center-Full
        run: |
          docker compose up -d --build
          sleep 60

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/EV-Server-Center.postman_collection.json
